//People would be formed by [peopleFirst] + [peopleSecond] + [peopleThird]

const { default: Services } = require("./server/Services")

"A dark night loomed during the amateur lacrosse tournament at which [firstPerson] was playing, deep within [firstPlace]."
//2nd sentence
"It was known that a certain artifact created by master artisan [secondPerson], [firstObject], would be on display in the [secondPlace]."
//3rd sentence
"Bad omens prevailed on that night, however. [thirdPerson], their heart full of jealousy, whipping out [secondObject], slew the good patron [firstPerson or secondPerson] in an act of ice-cold blood!"
//4th sentence
"I discerned that [thirdPerson] was the criminal at hand by finding their hair on [thirdObject]."

let peopleFirst = 
["Sir", 
"Larry", 
"Elizabeth",
"Doctor", 
"Dark Lord", 
"Your Worst Friend,", 
"Felicia", 
"Dracula",
"David",
"Drew",
"Haylee",
"Ashton",
"Monsieur",
"Madame",
"Their Majesty,",
"Special Agent",
"My Trusty Sidekick,",
"Evil Incarnate,",
"Ms. Leading",
"Captain",
"Head Chef",
"Hans",
"Sophie",
"Adele",
"Raphael",
"Ade",
"Oluwatobi",
"Mei",
"Huang",
"Takashi",
"Ai",
"Luong",
"Phuoc",
"Visionary Philosopher",
"Constable",
"Pirate King",
"Mr.",
"Mrs.",
"Lady",
"Viscount",
"Boyar",
"Prince",
"Practitioner of the Dark Arts,",
"Famed Art Thief",
"Ancient Wizard"]

let peopleSecond = 
["Delilah",
"'Fresh'",
"'Kingslayer'",
"Richter",
"Franglin",
"'Four-eyes'",
"'Crybaby'",
"Billiam",
"The Butcher",
"The Real Killer",
"'Big Thumb'",
"'Black Plastique'",
"'Loverboy'",
"'Red-Haired'",
"S.",
"'Thirsty'",
"'One Half'",
"D.",
"'Sudden Death'",
"'Musician'",
"'C H A I N S A W'"]

let peopleThird =
["Simmons",
", the doctoral candidate",
", who loves cheese",
"Nguyen",
", from the Western Isles",
", the class clown",
"Wiggles",
", the Jeopardy champion",
"Smith",
"Grantham",
"the Uncomfortable",
"Jr.",
"Esq.",
"Brown",
"Wang",
"Chen",
"Kumar",
"Khan",
"Ahmed",
"Garcia",
"Hernandez",
"Tran",
"Pradhan",
"Watanabe",
"Takahashi",
"Rossi",
"Esposito",
"Dubois",
"Bernard",
"Schneider",
"Wagner",
"Petrov",
"Popov",
"Azikiwe",
"Adejumo",
"Okeke",
"Okoye",
"Alberty",
"Kahele",
", the patron of the arts",
"the Nefarious",
"the Malign",
"the Unseen"]


//Places

//Places would be formed by [placesFirst] + [placesSecond]

let placesFirst =
["hated",
"fateful",
"disciplined",
"colorful",
"vestigial",
"gorgeous",
"practical",
"mysterious",
"divine",
"egregious",
"electric",
"punchable",
"thrifty",
"moody",
"solar",
"abyssal",
"aphotic",
"dandy",
"sweltering",
"infernal",
"antiquated",
"antediluvian",
"pluvial",
"foggy",
"ugly",
"simple",
"equine",
"effervescent",
"enigmatic"]

let placesSecond =
["VIP lounge",
"smoking room",
"room of bizarre collections",
"necromancy hall",
"swimming pool",
"secret passage",
"walk-in pantry",
"observatory",
"constable's quarters",
"stables",
"peasant's fields",
"doctor's office",
"den of sedition",
"remote work environment",
"lion enclosure",
"seltzer water factory",
"local burger joint",
"parlor",
"art gallery",
"billiards hall",
"courtroom",
"DMV",
"communal picnic area",
"breakroom",
"teacher's lounge",
"city-state",
"suburban neighborhood",
"bowling alley",
"farmer's market",
"dive bar",
"study",
"library",
"ballroom",
"phone booth",
"garage",
"game room",
"reservoir",
"quarry",
"dining room",
"master bedroom",
"casino",
"theatre",
"rose garden"
]


Objects

//Objects would be formed by [objectsFirst] + [objectsSecond] + [objectsThird]

let objectsFirst =
["a bowling ball",
"an archaic tome",
"the VHS",
"a coaster set",
"my personal computer",
"someone's overly huge smoking pipe",
"an expensive broach",
"a pair of reading glasses",
"a single willow branch",
"someone's vision of the future",
"the twisted spoon",
"a nightmare scenario",
"a big wishbone",
"my cheap airline tickets",
"your Subway order",
"a swift blade",
"Thor's hammer",
"a wickedly edged dagger",
"a Roman gladius",
"the family pocketwatch",
"an ice sculpture",
"a pristine revolver",
"a sharp scimitar",
"a cutlass",
"a dangerous shortsword",
"the candlestick holder",
"my mug from our roadtrip",
"a roaring chainsaw",
"the baseball bat",
"a flaming talon",
"my novel manuscript",
"a flying sword",
"an extra pair of arms",
"a glowing laser rifle",
"a lead pipe",
"a big wrench",
"my briefcase"]

let objectsSecond =
["that smelled like",
"welded with",
"powered by",
"built by early man from",
"with the aura of",
"covered in",
"smeared with",
"reminiscent of",
"containing",
"rife with",
"blessed with",
"plated with",
"coated in",
"pulled from the heart of",
"wrenched from the abyss by",
"derived from",
"containing",
"sponsored by",
"provided by",
"that tasted like",]

let objectsThird =
["the dark arts",
"historical misconceptions",
"praline",
"whispered secrets",
"dog food",
"a strange substance",
"PoliSci textbooks",
"sparkling water",
"shakshoukah",
"placid scenery",
"candy-coated chocolates",
"the efforts of honeybees",
"black coffee",
"the first leaves of spring",
"garden varieties of mint",
"fresh basil",
"temptation",
"expectations",
"spaghetti sauce",
"criminal intent",
"hopes and dreams",
"obsession",
"the single chance at life",
"a lone bullet",
"piracy",
"the god of darkness",
"amethyst light",
"legal action"]


for (i = 0; i<peopleFirst.length; i++){
    
}